MODULES = [
    {
        "id": "whistle-spoofing",
        "name": "whistle-Spoofing",
        "description": "Whistle Spoofing module",
        "path": "modules/whistle-spoofing",
        "status": "ready",
    },
    {
        "id": "aimbot",
        "name": "aimbot",
        "description": "Aimbot module",
        "path": "modules/aimbot",
        "status": "ready",
    },
    {
        "id": "auto-paint",
        "name": "auto-paint",
        "description": "Auto Paint module",
        "path": "modules/auto-paint",
        "status": "ready",
    },
    {
        "id": "esp",
        "name": "ESP",
        "description": "ESP module",
        "path": "modules/esp",
        "status": "ready",
    },
    {
        "id": "godmode",
        "name": "godmode",
        "description": "God Mode module",
        "path": "modules/godmode",
        "status": "ready",
    },
    {
        "id": "hide-anywhere",
        "name": "hide-Anywhere",
        "description": "Hide Anywhere module",
        "path": "modules/hide-anywhere",
        "status": "ready",
    },
    {
        "id": "noclip",
        "name": "noclip",
        "description": "Noclip module",
        "path": "modules/noclip",
        "status": "ready",
    },
]